[package]
name = "peach-packages-builder"
version = "0.1.0"
authors = ["Michael Williams <michael.williams@enspiral.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.29"
git2 = "0.8.0"
lazy_static = "1.3.0"
env_logger = "0.6.1"
rifling = "0.4.0"
log = "0.4.6"
snafu = "0.3.1"
